services:
  api:
    build:
      context: ../
      dockerfile: ./CodeReview.Devops/api-dockerfile
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8081:8081"
    expose:
      - "1234"
      - "8080"
      - "8081"
